name: Update Diagrams
on:
  push:
    paths:
      - '**.drawio'
jobs:
  update-diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Export draw.io files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: svg
          transparent: false
      - name: Debug - Show exported files
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of export directory (if it exists):"
          ls -la export/ || echo "No export directory found"
          find . -name "*.svg" -type f || echo "No SVG files found"
      - name: Move and rename exported file
        run: |
          mv export/Marketing_Analytics_Pipeline-Page-1.svg dataflow.svg
          rm -rf export/
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Update diagrams"
          git push
