name: Update Diagrams
on:
  push:
    paths:
      - '**.drawio'
jobs:
  update-diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Export draw.io files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
      - name: Move and rename exported file
        run: |
          mv export/Marketing_Analytics_Pipeline-Page-1.png dataflow.png
          rm -rf export/
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Update diagrams"
          git push
