name: Convert Draw.io to SVG

on:
  push:
    paths:
      - '**.drawio'
      - '**.draw.io'
  pull_request:
    paths:
      - '**.drawio'
      - '**.draw.io'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Export draw.io files to SVG
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: svg
          transparent: true
          embed-diagram: false

      - name: Commit and push SVG files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate SVG from draw.io files" && git push)
